markdown:            kramdown
highlighter:         pygments
permalink:           /:title
encoding:            utf-8

title:               'Pavel Kogan'
timezone:            Europe/London
paginate:            5

exclude:             [modules, Gemfile*]
include:             [_redirects]

author:
  name:              'Pavel Kogan'
  email:             pkogan@gmail.com
  profiles:
    - title:         'GitHub'
      url:           https://github.com/pavelkogan
    - title:         'Twitter'
      url:           https://twitter.com/pavel_kogan
    - title:         'LinkedIn'
      url:           https://uk.linkedin.com/in/pkogan

kramdown:
  input:             GFM

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
