markdown:         kramdown
highlighter:      pygments
permalink:        pretty
encoding:         utf-8
baseurl:          '/'

title:            'Pavel Kogan'
timezone:         Europe/London
paginate:         5

exclude:          [modules, Gemfile*]

author:
  name:           'Pavel Kogan'
  email:          pkogan@gmail.com
  profiles:
    - title:      'GitHub'
      url:        https://github.com/pavelkogan
    - title:      'Twitter'
      url:        https://twitter.com/pavel_kogan
    - title:      'LinkedIn'
      url:        https://uk.linkedin.com/in/pkogan

kramdown:
  input:          GFM

gems:
  - jekyll-sitemap
